
environment:
  matrix:
    - SMALLTALK: Squeak-trunk
    - SMALLTALK: Squeak-5.1
    - SMALLTALK: Squeak-5.0

matrix:
  fast_finish: true
  # Do we want this?
  allow_failures:
    - SMALLTALK: Squeak-trunk

platform:
  - x86

clone_depth: 5
build: false
# maybe 'tests'
version: "{build}"
